/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.tmpotter.ui.dialogs;

import javax.swing.JPanel;


/**
 * 
 * @author Hiroshi Miura
 */
public class ImportWizardSelectTypePanel extends JPanel implements IImportWizardPanel {
	public static final String id = "selecttype";

	/**
	 * Creates new form ImportWizardSelectTypePanel
	 */
	public ImportWizardSelectTypePanel() {
		initComponents();
	}
	
	public String getId() {
		return id;
	}

	public JPanel getPanel() {
		return this;
	}

	public String getNextFinishCommand() {
		return getSelection();
	}
	
	public String getBackCommand() {
		return null;
	}

	public String getSelection() {
		return buttonGroup.getSelection().getActionCommand();
	}
	
	public void updatePref() {
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup = new javax.swing.ButtonGroup();
                panelBiText = new javax.swing.JPanel();
                radioButtonPlain = new javax.swing.JRadioButton();
                labelDescPlain = new javax.swing.JLabel();
                panelSingle = new javax.swing.JPanel();
                radioButtonPO = new javax.swing.JRadioButton();
                labelDescPO = new javax.swing.JLabel();

                setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

                panelBiText.setBorder(javax.swing.BorderFactory.createTitledBorder("Bi-Text imports"));
                panelBiText.setLayout(new java.awt.GridLayout(1, 0));

                buttonGroup.add(radioButtonPlain);
                radioButtonPlain.setSelected(true);
                radioButtonPlain.setText("Plain text fies");
                radioButtonPlain.setActionCommand("bi-text");
                panelBiText.add(radioButtonPlain);

                labelDescPlain.setText("Load bi text file and align line-by-line.");
                panelBiText.add(labelDescPlain);

                add(panelBiText);

                panelSingle.setBorder(javax.swing.BorderFactory.createTitledBorder("Single file import"));
                panelSingle.setLayout(new java.awt.GridLayout(1, 0));

                buttonGroup.add(radioButtonPO);
                radioButtonPO.setText("PO file");
                radioButtonPO.setActionCommand("pofile");
                panelSingle.add(radioButtonPO);

                labelDescPO.setText("Load PO message catalog file.");
                panelSingle.add(labelDescPO);

                add(panelSingle);
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.ButtonGroup buttonGroup;
        private javax.swing.JLabel labelDescPO;
        private javax.swing.JLabel labelDescPlain;
        private javax.swing.JPanel panelBiText;
        private javax.swing.JPanel panelSingle;
        private javax.swing.JRadioButton radioButtonPO;
        private javax.swing.JRadioButton radioButtonPlain;
        // End of variables declaration//GEN-END:variables
}
