/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.tmpotter.ui;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.reflect.Field;
import javax.swing.JButton;
import static org.openide.awt.Mnemonics.setLocalizedText;
import static org.tmpotter.util.Localization.getString;

/**
 * Toolbar UI.
 *
 * @author Hiroshi Miura
 */
public class AlignToolBar extends javax.swing.JPanel implements ActionListener {

    private ModelMediator modelMediator;

    /**
     * Creates new form AlignToolBar
     */
    public AlignToolBar() {
        initComponents();
    }

    /**
     * Set 'actionCommand' for all menu items.
     */
    protected void setActionCommands() {
        try {
            for (Field f : this.getClass().getDeclaredFields()) {
                if (JButton.class.isAssignableFrom(f.getType())) {
                    JButton button = (JButton) f.get(this);
                    button.setActionCommand(f.getName());
                    button.addActionListener(this);
                }
            }
        } catch (IllegalAccessException ex) {
            throw new ExceptionInInitializerError(ex);
        }
    }

    public void setModelMediator(ModelMediator mediator) {
        this.modelMediator = mediator;
    }

    @Override
    public final void actionPerformed(final ActionEvent action) {
        final Object actor = action.getSource();

        if (actor instanceof JButton) {
            if (actor == buttonOriginalDelete) {
                modelMediator.onOriginalDelete();
            } else if (actor == buttonOriginalJoin) {
                modelMediator.onOriginalJoin();
            } else if (actor == buttonOriginalSplit) {
                modelMediator.onOriginalSplit();
            } else if (actor == buttonTranslationDelete) {
                modelMediator.onTranslationDelete();
            } else if (actor == buttonTranslationJoin) {
                modelMediator.onTranslationJoin();
            } else if (actor == buttonTranslationSplit) {
                modelMediator.onTranslationSplit();
            } else if (actor == buttonRemoveBlankRows) {
                modelMediator.onRemoveBlankRows();
            } else if (actor == buttonTUSplit) {
                modelMediator.onTuSplit();
            } else if (actor == buttonUndo) {
                modelMediator.undoChanges();
                modelMediator.onUndo();
            }
        }
    }

    final void setFonts( final Font font ) {
	buttonUndo               .setFont( font );
	buttonRemoveBlankRows    .setFont( font );
	buttonTUSplit            .setFont( font );
	buttonOriginalJoin       .setFont( font );
	buttonOriginalDelete     .setFont( font );
	buttonOriginalSplit      .setFont( font );
	buttonTranslationJoin    .setFont( font );
	buttonTranslationDelete  .setFont( font );
	buttonTranslationSplit   .setFont( font );
    }

    final void enableButtons(boolean enabled) {
        buttonRemoveBlankRows.setEnabled(enabled);
        buttonTUSplit.setEnabled(enabled);
        buttonOriginalJoin.setEnabled(enabled);
        buttonOriginalDelete.setEnabled(enabled);
        buttonOriginalSplit.setEnabled(enabled);
        buttonTranslationJoin.setEnabled(enabled);
        buttonTranslationDelete.setEnabled(enabled);
        buttonTranslationSplit.setEnabled(enabled);
    }

    public final void setUndoEnabled(boolean enabled) {
        buttonUndo.setEnabled(enabled);
    }

    public final void setOriginalJoinEnabled(boolean enabled) {
        buttonOriginalJoin.setEnabled(enabled);
    }

    public final void setTranslationJoinEnabled(boolean enabled) {
        buttonTranslationJoin.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                toolBar = new javax.swing.JToolBar();
                panelOriginal = new javax.swing.JPanel();
                buttonOriginalDelete = new javax.swing.JButton();
                buttonOriginalJoin = new javax.swing.JButton();
                buttonOriginalSplit = new javax.swing.JButton();
                panelTranslateUnit = new javax.swing.JPanel();
                buttonRemoveBlankRows = new javax.swing.JButton();
                buttonTUSplit = new javax.swing.JButton();
                buttonUndo = new javax.swing.JButton();
                jSeparator1 = new javax.swing.JToolBar.Separator();
                panelTranslation = new javax.swing.JPanel();
                buttonTranslationDelete = new javax.swing.JButton();
                buttonTranslationJoin = new javax.swing.JButton();
                buttonTranslationSplit = new javax.swing.JButton();

                toolBar.setRollover(true);
                toolBar.setMaximumSize(new java.awt.Dimension(1000, 94));
                toolBar.setMinimumSize(new java.awt.Dimension(640, 48));
                toolBar.setPreferredSize(new java.awt.Dimension(640, 64));

                panelOriginal.setBorder(javax.swing.BorderFactory.createTitledBorder("Original"));
                panelOriginal.setMaximumSize(new java.awt.Dimension(340, 90));
                panelOriginal.setMinimumSize(new java.awt.Dimension(240, 0));
                panelOriginal.setPreferredSize(new java.awt.Dimension(220, 90));

                buttonOriginalDelete.setText("Delete");
                setLocalizedText(buttonOriginalDelete, getString("BTN.DELETE.ORIGINAL"));

                buttonOriginalJoin.setText("Join");
                setLocalizedText(buttonOriginalJoin, getString("BTN.JOIN.ORIGINAL"));

                buttonOriginalSplit.setText("Split");
                setLocalizedText(buttonOriginalSplit, getString("BTN.SPLIT.ORIGINAL"));

                javax.swing.GroupLayout panelOriginalLayout = new javax.swing.GroupLayout(panelOriginal);
                panelOriginal.setLayout(panelOriginalLayout);
                panelOriginalLayout.setHorizontalGroup(
                        panelOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelOriginalLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(buttonOriginalDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonOriginalJoin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonOriginalSplit)
                                .addContainerGap(24, Short.MAX_VALUE))
                );
                panelOriginalLayout.setVerticalGroup(
                        panelOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelOriginalLayout.createSequentialGroup()
                                .addGroup(panelOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonOriginalDelete)
                                        .addComponent(buttonOriginalJoin)
                                        .addComponent(buttonOriginalSplit))
                                .addGap(0, 11, Short.MAX_VALUE))
                );

                toolBar.add(panelOriginal);

                panelTranslateUnit.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit"));
                panelTranslateUnit.setMaximumSize(new java.awt.Dimension(500, 90));
                panelTranslateUnit.setMinimumSize(new java.awt.Dimension(280, 0));
                panelTranslateUnit.setPreferredSize(new java.awt.Dimension(310, 90));
                panelTranslateUnit.setRequestFocusEnabled(false);

                buttonRemoveBlankRows.setText("Delete Blank Rows");
                setLocalizedText(buttonRemoveBlankRows, getString("BTN.DELETE.BLANK.ROWS"));

                buttonTUSplit.setText("Split");
                setLocalizedText(buttonTUSplit, getString("BTN.SPLIT.TU"));

                buttonUndo.setMnemonic('Z');
                buttonUndo.setText("Undo");
                setLocalizedText(buttonUndo, getString("BTN.UNDO"));
                buttonUndo.setEnabled(false);
                buttonUndo.setFocusable(false);
                buttonUndo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                buttonUndo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                javax.swing.GroupLayout panelTranslateUnitLayout = new javax.swing.GroupLayout(panelTranslateUnit);
                panelTranslateUnit.setLayout(panelTranslateUnitLayout);
                panelTranslateUnitLayout.setHorizontalGroup(
                        panelTranslateUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTranslateUnitLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(buttonRemoveBlankRows)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonTUSplit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonUndo)
                                .addContainerGap(8, Short.MAX_VALUE))
                );
                panelTranslateUnitLayout.setVerticalGroup(
                        panelTranslateUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTranslateUnitLayout.createSequentialGroup()
                                .addGroup(panelTranslateUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelTranslateUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(buttonRemoveBlankRows)
                                                .addComponent(buttonTUSplit))
                                        .addComponent(buttonUndo))
                                .addGap(0, 11, Short.MAX_VALUE))
                );

                toolBar.add(panelTranslateUnit);
                panelTranslateUnit.getAccessibleContext().setAccessibleName("Translation");

                toolBar.add(jSeparator1);

                panelTranslation.setBorder(javax.swing.BorderFactory.createTitledBorder("Translation"));
                panelTranslation.setMinimumSize(new java.awt.Dimension(180, 90));
                panelTranslation.setPreferredSize(new java.awt.Dimension(220, 90));

                buttonTranslationDelete.setText("Delete");
                setLocalizedText(buttonTranslationDelete, getString("BTN.DELETE.TRANSLATION"));

                buttonTranslationJoin.setText("Join");
                setLocalizedText(buttonTranslationJoin, getString("BTN.JOIN.TRANSLATION"));

                buttonTranslationSplit.setText("Split");
                setLocalizedText(buttonTranslationSplit, getString("BTN.SPLIT.TRANSLATION"));

                javax.swing.GroupLayout panelTranslationLayout = new javax.swing.GroupLayout(panelTranslation);
                panelTranslation.setLayout(panelTranslationLayout);
                panelTranslationLayout.setHorizontalGroup(
                        panelTranslationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTranslationLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(buttonTranslationDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonTranslationJoin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonTranslationSplit)
                                .addContainerGap(18, Short.MAX_VALUE))
                );
                panelTranslationLayout.setVerticalGroup(
                        panelTranslationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTranslationLayout.createSequentialGroup()
                                .addGroup(panelTranslationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonTranslationDelete)
                                        .addComponent(buttonTranslationJoin)
                                        .addComponent(buttonTranslationSplit))
                                .addGap(0, 41, Short.MAX_VALUE))
                );

                toolBar.add(panelTranslation);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton buttonOriginalDelete;
        private javax.swing.JButton buttonOriginalJoin;
        private javax.swing.JButton buttonOriginalSplit;
        private javax.swing.JButton buttonRemoveBlankRows;
        private javax.swing.JButton buttonTUSplit;
        private javax.swing.JButton buttonTranslationDelete;
        private javax.swing.JButton buttonTranslationJoin;
        private javax.swing.JButton buttonTranslationSplit;
        private javax.swing.JButton buttonUndo;
        private javax.swing.JToolBar.Separator jSeparator1;
        private javax.swing.JPanel panelOriginal;
        private javax.swing.JPanel panelTranslateUnit;
        private javax.swing.JPanel panelTranslation;
        private javax.swing.JToolBar toolBar;
        // End of variables declaration//GEN-END:variables
}
