/* *************************************************************************
 *
 *  TMPotter - Bi-text Aligner/TMX Editor
 *
 *  Copyright (C) 2016 Hiroshi Miura
 *
 *  This file is part of TMPotter.
 *
 *  TMPotter is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  TMPotter is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with TMPotter.  If not, see http://www.gnu.org/licenses/.
 *
 * *************************************************************************/

package org.tmpotter.ui.wizard;

import javax.swing.JPanel;


/**
 * 
 * @author Hiroshi Miura
 */
public class ImportWizardSelectTypePanel extends JPanel implements IImportWizardPanel {
	public static final String id = "selecttype";

	/**
	 * Creates new form ImportWizardSelectTypePanel
	 */
	public ImportWizardSelectTypePanel() {
		initComponents();
	}
	
	public String getId() {
		return id;
	}

	public JPanel getPanel() {
		return this;
	}

	public String getNextFinishCommand() {
		return getSelection();
	}
	
	public String getBackCommand() {
		return null;
	}

	public String getSelection() {
		return buttonGroup.getSelection().getActionCommand();
	}
	
	public void updatePref() {
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup = new javax.swing.ButtonGroup();
                panelBiText = new javax.swing.JPanel();
                radioButtonPlain = new javax.swing.JRadioButton();
                labelDescPlain = new javax.swing.JLabel();
                panelSingle = new javax.swing.JPanel();
                radioButtonPO = new javax.swing.JRadioButton();
                labelDescPO = new javax.swing.JLabel();
                radioButtonTmx = new javax.swing.JRadioButton();
                labelDescTmx = new javax.swing.JLabel();

                setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

                panelBiText.setBorder(javax.swing.BorderFactory.createTitledBorder("Bi-Text imports"));
                panelBiText.setLayout(new java.awt.GridLayout(1, 0));

                buttonGroup.add(radioButtonPlain);
                radioButtonPlain.setSelected(true);
                radioButtonPlain.setText("Plain text fies");
                radioButtonPlain.setActionCommand(ImportWizardBiTextFile.id);
                panelBiText.add(radioButtonPlain);

                labelDescPlain.setText("Load bi text file and align line-by-line.");
                panelBiText.add(labelDescPlain);

                add(panelBiText);

                panelSingle.setBorder(javax.swing.BorderFactory.createTitledBorder("Single file import"));
                panelSingle.setLayout(new java.awt.GridLayout(2, 2));

                buttonGroup.add(radioButtonPO);
                radioButtonPO.setText("PO file");
                radioButtonPO.setActionCommand(ImportWizardPOFile.id);
                panelSingle.add(radioButtonPO);

                labelDescPO.setText("Load PO message catalog file.");
                panelSingle.add(labelDescPO);

                buttonGroup.add(radioButtonTmx);
                radioButtonTmx.setText("TMX file");
                radioButtonTmx.setActionCommand(ImportWizardTmxFile.id);
                panelSingle.add(radioButtonTmx);

                labelDescTmx.setText("Load TMX file.");
                panelSingle.add(labelDescTmx);

                add(panelSingle);
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.ButtonGroup buttonGroup;
        private javax.swing.JLabel labelDescPO;
        private javax.swing.JLabel labelDescPlain;
        private javax.swing.JLabel labelDescTmx;
        private javax.swing.JPanel panelBiText;
        private javax.swing.JPanel panelSingle;
        private javax.swing.JRadioButton radioButtonPO;
        private javax.swing.JRadioButton radioButtonPlain;
        private javax.swing.JRadioButton radioButtonTmx;
        // End of variables declaration//GEN-END:variables
}
